services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Change this value to the connection string if not using MongoDB container
        NEXT_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/${MONGO_INITDB_DATABASE}?authSource=admin
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Change this value to the connection string if not using MongoDB container
      NEXT_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - samay-network

  database:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - samay-data:/data/db
    env_file:
      - .env
    networks:
      - samay-network

volumes:
  samay-data:

networks:
  samay-network:
